#! /bin/sh
killall -q -9 sxhkd redshift polybar

sxhkd &
polybar thinkpad &
xsetroot -cursor_name left_ptr &
redshift &

bspc monitor -d 一 二 三 四 五 六 七 

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio              0.50

bspc config single_monocle           true
bspc config borderless_monocle       true
bspc config gapless_monocle          true
bspc config focus_follows_pointer    true

bspc config normal_border_color    "#eeeeee"
bspc config active_border_color    "#000000"
bspc config focused_border_color   "#000000"
bspc config presel_feedback_color  "#eeeeee"

bspc rule -a Chromium          desktop='^1'
bspc rule -a mpv               desktop='^5'

sleep 1
dunstify "Hello" "bpwmrc loaded"
